// Transcript generation logic
function generateTranscript() {
    const output = document.getElementById('transcriptOutput');

    if (Object.values(currentPlan.courses).every(year => year.length === 0)) {
        output.innerHTML = `
            <div class="empty-transcript">
                <h3>No Courses Added</h3>
                <p>Please add courses in the Planner tab first.</p>
            </div>
        `;
        return;
    }

    const overallStats = calculateOverallStats();

    let html = `
        <div class="modern-transcript">

            <div class="transcript-paper">

                <!-- HEADER -->
                <header class="transcript-header">
                    <div>
                        <h1>${currentPlan.schoolName}</h1>
                        <p class="subtitle">Official High School Transcript</p>
                    </div>

                    <div class="transcript-date">
                        <span>Issued:</span>
                        <strong>${new Date().toLocaleDateString()}</strong>
                    </div>
                </header>

                <!-- STUDENT INFO -->
                <section class="student-info">
                    <div class="info-card">
                        <label>Student Name</label>
                        <span>${currentPlan.studentName}</span>
                    </div>

                    <div class="info-card">
                        <label>Graduation Year</label>
                        <span>${currentPlan.graduationYear}</span>
                    </div>

                    <div class="info-card">
                        <label>Cumulative GPA</label>
                        <span>${overallStats.cumulativeGPA}</span>
                    </div>

                    <div class="info-card">
                        <label>Total Credits</label>
                        <span>${overallStats.totalCredits}</span>
                    </div>
                </section>
    `;

    // YEAR SECTIONS
    CONFIG.YEARS.forEach(year => {
        const courses = currentPlan.courses[year.number] || [];

        if (courses.length === 0) return;

        const yearStats = calculateYearStats(courses);

        html += `
            <section class="year-section">
                <div class="year-header">
                    <h2>${year.name}</h2>

                    <div class="year-stats">
                        <span><strong>Credits:</strong> ${yearStats.credits}</span>
                        <span><strong>GPA:</strong> ${yearStats.gpa}</span>
                    </div>
                </div>

                <table class="transcript-table">
                    <thead>
                        <tr>
                            <th>Course</th>
                            <th>Year</th>
                            <th>Semester</th>
                            <th>Type</th>
                            <th>Credits</th>
                            <th>Grade</th>
                            <th>GPA</th>
                        </tr>
                    </thead>

                    <tbody>
        `;

        courses.forEach(course => {
            const gpaDisplay =
                course.gpaPoints !== null
                    ? course.gpaPoints.toFixed(1)
                    : 'P';

            html += `
                <tr>
                    <td>${course.name}</td>
                    <td>${course.schoolYear || '-'}</td>
                    <td>${course.courseSemester || '-'}</td>
                    <td>${course.courseType || 'Regular'}</td>
                    <td>${course.credits}</td>
                    <td>
                        <span class="grade-badge grade-${course.grade}">
                            ${course.grade}
                        </span>
                    </td>
                    <td>${gpaDisplay}</td>
                </tr>
            `;
        });

        html += `
                    </tbody>
                </table>
            </section>
        `;
    });

    // FINAL SUMMARY
    html += `
            <section class="overall-summary">
                <h2>Academic Summary</h2>

                <div class="summary-grid">
                    <div class="summary-card">
                        <label>Total Courses</label>
                        <strong>${overallStats.totalCourses}</strong>
                    </div>

                    <div class="summary-card">
                        <label>Total Credits</label>
                        <strong>${overallStats.totalCredits}</strong>
                    </div>

                    <div class="summary-card">
                        <label>Cumulative GPA</label>
                        <strong>${overallStats.cumulativeGPA}</strong>
                    </div>
                </div>
            </section>

            <footer class="transcript-footer">
                <p>
                    This transcript was generated by HomeschoolHS Planner.
                </p>
            </footer>

        </div>
    </div>
    `;

    output.innerHTML = html;
}

function calculateYearStats(courses) {
    let credits = 0;
    let gpaPoints = 0;
    let gradedCredits = 0;

    courses.forEach(course => {
        credits += course.credits;
        if (course.gpaPoints !== null) {
            gpaPoints += course.gpaPoints * course.credits;
            gradedCredits += course.credits;
        }
    });

    const gpa = gradedCredits > 0 ? gpaPoints / gradedCredits : 0;

    return {
        credits: credits.toFixed(1),
        gpa: formatGPA(gpa)
    };
}

function calculateOverallStats() {
    let totalCredits = 0;
    let totalGPAPoints = 0;
    let totalGradedCredits = 0;
    let totalCourses = 0;

    CONFIG.YEARS.forEach(year => {
        const courses = currentPlan.courses[year.number] || [];
        courses.forEach(course => {
            totalCourses++;
            totalCredits += course.credits;
            if (course.gpaPoints !== null) {
                totalGPAPoints += course.gpaPoints * course.credits;
                totalGradedCredits += course.credits;
            }
        });
    });

    const cumulativeGPA = totalGradedCredits > 0 ? totalGPAPoints / totalGradedCredits : 0;

    return {
        totalCredits: totalCredits.toFixed(1),
        cumulativeGPA: formatGPA(cumulativeGPA),
        totalCourses: totalCourses
    };
}

function printTranscript() {
    if (document.getElementById('transcriptOutput').innerHTML === '') {
        alert('Please generate a transcript first');
        return;
    }
    window.print();
}
